substitutions:
  name: esp-poe-zb-v201
  friendly_name: "ESP32 PoE ZigBee Gateway v2.01"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

  #name_add_mac_suffix: true

  project:
    name: "ficueu.esp-poe-zb-v201"
    version: "2.01"

  on_boot:
    priority: 800.0
    then:
      - output.turn_off: zbBSL
      - output.turn_off: zbRST
      
esp32:
  board: esp32dev
  framework:
    type: esp-idf

dashboard_import:
  package_import_url: github://ficueu/ESP-POE-ZB-v2.0/esp-poe-zb-v201.yaml@main
  import_full_config: true

logger:

api:
  reboot_timeout: 0s

debug:
  update_interval: 60s

ota:
  - platform: esphome

status_led:
  pin:
    number: 2
    inverted: true
    
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    mode: CLK_OUT
    pin: GPIO17
  phy_addr: 1
  power_pin: GPIO12
  
web_server:
  port: 80
  version: 1

sensor:
  - platform: uptime
    name: GW uptime
  - platform: debug
    free:
      name: "Heap Free" 

  - platform: adc
    attenuation: 11dB
    filters:
      - multiply: 20.6
    pin: GPIO35
    name: "Bus Voltage"
    update_interval: 60s
   
external_components:
  - source: github://oxan/esphome-stream-server


button:
  - platform: restart
    name: "Gateway restart"
    id: gwrst

  - platform: template
    name: "ZigBee force update"
    on_press:
      - switch.turn_on: disrst
      - output.turn_on: zbBSL
      - delay: 100ms
      - output.turn_on: zbRST
      - delay: 100ms
      - output.turn_off: zbRST
      - delay: 100ms
      - output.turn_off: zbBSL
      - delay: 100ms
      - logger.log: "Done. Please update FW now."

  - platform: output
    name: "ZigBee reset"
    output: zbRST
    id: btnzbRST
    duration: 1s
    on_press: 
      then:
        - logger.log: "Zigbee module reset."

output:
  - platform: gpio
    pin: 32
    id: zbRST
    inverted: yes
  - platform: gpio
    pin: 33
    id: zbBSL
    inverted: yes

number:
  - platform: template
    min_value:  0
    max_value: 2
    step: 1
    initial_value: 0
    id: streamcnt
    optimistic: True
    on_value:
      then:
        - if:
            condition:
              number.in_range:
                id: streamcnt
                above: 1.1
            then:
              - if:
                  condition:
                    - switch.is_off: disrst
                  then:
                    - button.press: gwrst

binary_sensor:
  - platform: stream_server
    connected:
      name: "ZB client connected"
      on_press:
        then:
          - if:
              condition:
                - switch.is_off: disrst
              then:
                - button.press: btnzbRST
      on_release:
        then:
          - number.increment: streamcnt
    stream_server: zigbee_stream

switch:
  - platform: template
    name: "Disable auto reset"
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: True
    id: disrst
 
stream_server:
  id: zigbee_stream
  uart_id: ZIGBEE
  port: 1234
    
#UART Settings
uart:
  - id: ZIGBEE
    rx_pin: GPIO4
    tx_pin: GPIO5
    baud_rate: 115200    

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms

bluetooth_proxy:
  active: true